# Generated by Django 3.1.5 on 2021-08-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0005_empiricalmeasuresb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empiricalmeasuresb',
            old_name='ewald_energy',
            new_name='ewald_energya',
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energye',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
