# Generated by Django 3.1.5 on 2021-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0006_auto_20210810_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
