# Generated by Django 3.1.5 on 2021-08-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0007_empiricalmeasuresb_ewald_energyg'),
    ]

    operations = [
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='bond_lengthx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='bond_lengthy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='bond_lengthz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='csm_alpha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='csm_beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='csm_gamma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
