# Generated by Django 3.1.5 on 2021-08-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0008_auto_20210810_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpiricalMeasuresC',
            fields=[
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Completed'), ('F', 'Failed')], default='S', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ewald_energya', models.FloatField(blank=True, null=True)),
                ('ewald_energyb', models.FloatField(blank=True, null=True)),
                ('ewald_energyc', models.FloatField(blank=True, null=True)),
                ('ewald_energyd', models.FloatField(blank=True, null=True)),
                ('ewald_energye', models.FloatField(blank=True, null=True)),
                ('ewald_energyf', models.FloatField(blank=True, null=True)),
                ('ewald_energyg', models.FloatField(blank=True, null=True)),
                ('bond_lengthx', models.FloatField(blank=True, null=True)),
                ('bond_lengthy', models.FloatField(blank=True, null=True)),
                ('bond_lengthz', models.FloatField(blank=True, null=True)),
                ('csm_alpha', models.FloatField(blank=True, null=True)),
                ('csm_beta', models.FloatField(blank=True, null=True)),
                ('csm_gamma', models.FloatField(blank=True, null=True)),
                ('pathway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diffusion.pathway')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
