# Generated by Django 3.1.5 on 2021-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0009_empiricalmeasuresc'),
    ]

    operations = [
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresb',
            name='ewald_energyj',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
