# Generated by Django 3.1.5 on 2021-08-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0010_auto_20210811_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empiricalmeasuresb',
            name='ewald_energyh',
        ),
        migrations.RemoveField(
            model_name='empiricalmeasuresb',
            name='ewald_energyi',
        ),
        migrations.RemoveField(
            model_name='empiricalmeasuresb',
            name='ewald_energyj',
        ),
        migrations.AddField(
            model_name='empiricalmeasuresc',
            name='ewald_energyh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresc',
            name='ewald_energyi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empiricalmeasuresc',
            name='ewald_energyj',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
