# Generated by Django 3.1.5 on 2021-09-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0011_auto_20210811_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('formula_reduced', models.CharField(blank=True, max_length=50, null=True)),
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diffusion.materialsprojectstructure')),
            ],
        ),
    ]
