# Generated by Django 3.1.5 on 2021-10-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0013_prototype2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diffusion.materialsprojectstructure')),
            ],
        ),
    ]
