# Generated by Django 3.1.5 on 2021-10-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0014_prototype3'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatProjData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_gap', models.FloatField(blank=True, null=True)),
                ('cost_per_mol', models.FloatField(blank=True, null=True)),
                ('cost_per_kg', models.FloatField(blank=True, null=True)),
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diffusion.materialsprojectstructure')),
            ],
        ),
    ]
