# Generated by Django 3.1.5 on 2021-10-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0015_matprojdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpCorBarrier',
            fields=[
                ('barrier', models.FloatField(blank=True, null=True)),
                ('pathway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diffusion.pathway')),
            ],
        ),
    ]
