# Generated by Django 3.1.5 on 2021-10-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0017_hostlattice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('length', models.FloatField(blank=True, null=True)),
                ('barrier', models.FloatField(blank=True, null=True)),
                ('pathway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diffusion.pathway')),
            ],
        ),
    ]
